import java.util.List;

public class ConcreteStrategyTime implements Strategy {

    @Override
    public Server addTask(List<Server> servers, Task task) {
       //autogenerated method stub
        return null;
    }

    public enum SelectionPolicy{
        SHORTEST_QUEUE, SHORTEST_TIME
    }
}
